DaVinxi/Models/Production/Batch/MasterBatch.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DaVinxi.Models
{
    public class MasterBatch
    {
        public MasterBatch()
        {
            start_date = finish_date = created_date = revised_date = DateTime.Now;
        }

        [Key]
        [Column(Order = 0)]
        [Index("CompanyIndex")]
        [Display(Name="Company")]
        [Required]
        public int company_id { get; set; }

        [Key]
        [Column(Order = 1)]
        [Index("BatchIndex")]
        [Display(Name = "Batch ID")]
        [Required]
        public string batch_id { get; set; }

        [Required, Index("MachineIndex"), MaxLength(128)]
        public string machine_id { get; set; }

        [Required]
        [MaxLength(128)]
        [Index("SKUIndex")]
        public string sku_id { get; set; }

        [Required]
        [DataType(System.ComponentModel.DataAnnotations.DataType.DateTime)]
        [Display(Name = "Start Date")]
        public DateTime start_date { get; set; }

        [Required]
        [DataType(System.ComponentModel.DataAnnotations.DataType.DateTime)]
        [Display(Name = "Finish Date")]
        public DateTime finish_date { get; set; }

        [Required]
        [DataType(System.ComponentModel.DataAnnotations.DataType.DateTime)]
        public DateTime created_date { get; set; }

        [Required]
        [DataType(System.ComponentModel.DataAnnotations.DataType.DateTime)]
        public DateTime revised_date { get; set; }

        [Required]
        public string revised_by { get; set; }
    }
}

DaVinxi/Controllers/BatchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DaVinxi.Models;

namespace DaVinxi.Controllers
{
    public class BatchController : Controller
    {
        private MyDBContext _DB;
        public MyDBContext DB
        {
            get
            {
                if (_DB == null)
                    _DB = new MyDBContext();
                return _DB;
            }
        }

        private HelperClassController _Helper;
        public HelperClassController Helper
        {
            get
            {
                if (_Helper == null)
                    _Helper = new HelperClassController(DB);
                return _Helper;
            }
        }


        [Authorize]
        // GET: Batch
        public ActionResult Index()
        {
            int CompanyID = Request.Cookies["company_id"] != null &&
                int.Parse(Request.Cookies["company_id"].Value) > 0 ?
                int.Parse(Request.Cookies["company_id"].Value) : 0;

            ViewBag.Companies = Helper.GetCompanies(CompanyID);

            return View();
        }

        [Authorize]
        public ActionResult Register()
        {
            ViewBag.Companies = Helper.GetCompanies(Request.Cookies["company_id"] != null &&
                int.Parse(Request.Cookies["company_id"].Value) > 0 ?
                int.Parse(Request.Cookies["company_id"].Value) : 0);
            MasterBatch NewBatch = new MasterBatch();
            NewBatch.revised_by = User.Identity.Name;
            return View(NewBatch);
        }

        [Authorize]
        [HttpPost]
        public ActionResult Register(MasterBatch registerBatch)
        {
            if(ModelState.IsValid)
            {
                if (DB.Batches.Where(b => b.company_id == registerBatch.company_id && 
                    string.Compare(b.batch_id, registerBatch.batch_id, true) == 0).Count() > 0)
                    ModelState.AddModelError("exist", "Batch already exist");
                else
                {
                    registerBatch.revised_by = User.Identity.Name;
                    DB.Batches.Add(registerBatch);
                    DB.SaveChanges();
                    return RedirectToAction("Index");
                }
            }

            ViewBag.Companies = Helper.GetCompanies(Request.Cookies["company_id"] != null &&
                int.Parse(Request.Cookies["company_id"].Value) > 0 ?
                int.Parse(Request.Cookies["company_id"].Value) : 0);
            return View(registerBatch);
        }

        [Authorize]
        public ActionResult Update(int companyID,string batchID)
        {
            MasterBatch Batch = DB.Batches.Where(b => b.company_id == companyID && 
                string.Compare(b.batch_id, batchID, true) == 0).FirstOrDefault();

            if (Batch == null)
                return RedirectToAction("Index");

            return View(Batch);
        }

        [Authorize]
        [HttpPost]
        public ActionResult Update(MasterBatch updatedBatch)
        {
            if (ModelState.IsValid)
            {
                MasterBatch Batch = DB.Batches.Where(b => b.company_id == updatedBatch.company_id &&
                    string.Compare(b.batch_id, updatedBatch.batch_id, true) == 0).FirstOrDefault();

                if (Batch != null)
                {
                    bool IsDirty = false;

                    if(string.Compare(Batch.sku_id,updatedBatch.sku_id,true)!=0)
                    {
                        Batch.sku_id = updatedBatch.sku_id;
                        IsDirty = true;
                    }

                    if (string.Compare(Batch.machine_id, updatedBatch.machine_id, true) != 0)
                    {
                        Batch.machine_id = updatedBatch.machine_id;
                        IsDirty = true;
                    }

                    if (updatedBatch.start_date.Subtract(Batch.start_date).TotalMinutes != 0)
                    {
                        Batch.start_date = updatedBatch.start_date;
                        IsDirty = true;
                    }

                    if (updatedBatch.finish_date.Subtract(Batch.finish_date).TotalMinutes != 0)
                    {
                        Batch.finish_date = updatedBatch.finish_date;
                        IsDirty = true;
                    }

                    if (IsDirty)
                    {
                        DB.Entry(Batch).State = System.Data.Entity.EntityState.Modified;
                        DB.SaveChanges();
                    }
                }

                return RedirectToAction("Index");
            }

            return View(updatedBatch);
        }

        [Authorize]
        [HttpPost]
        public ActionResult Delete(int companyID,string batchID)
        {
            string SQL = string.Format("exec [dbo].[DeleteBatch] @companyID={0},@batchID='{1}'", companyID, batchID);
            DB.Database.ExecuteSqlCommand(SQL);

            return RedirectToAction("Index");
        }
    }
}

DaVinxi/Views/Batch/Register.cshtml
@model DaVinxi.Models.MasterBatch

@{
    ViewBag.Title = "Register New Batch";
}

<script type="text/javascript">
    function GetSKU() {
        $.ajax
            (
                {
                    type: "POST",
                    url: '@Url.Action("GetSKUJSON", "HelperClass")',
                    data: {
                        companyID: $("#companies").val()
                    },
                    dataType: 'json',
                    async: true,
                    beforeSend: function (xhr) {
                        $("#skus").html('');
                    }
                }
            ).done
            (
                function (data) {
                    if (data != null && data.length > 0) {
                        for (var i = 0; i < data.length; i++) {
                            $("#skus").append("<option value='" + data[i].sku_id + "'>[" + data[i].sku_id + "] " +
                                data[i].sku_name + "</option>");
                        }
                    }
                    $("#skus").selectpicker("refresh");
                }
            );
    }

    function GetMachine() {
        $.ajax
            (
                {
                    type: "POST",
                    url: '@Url.Action("GetMachinesJSON", "HelperClass")',
                    data: {
                        companyID: $("#companies").val()
                    },
                    dataType: 'json',
                    async: true,
                    beforeSend: function (xhr) {
                        $("#machines").html('');
                    }
                }
            ).done
            (
                function (data) {
                    if (data != null && data.length > 0) {
                        for (var i = 0; i < data.length; i++) {
                            $("#machines").append("<option value='" + data[i].machine.machine_id + "'>" +
                                data[i].machine.machine_name + "</option>");
                        }
                    }
                    $("#machines").selectpicker("refresh");
                }
            );
    }

    $
        (
            function()
            {
                $(".datepicker").datetimepicker(
                    {
                        format: 'MMMM DD YYYY HH:mm'
                    });
                $("#startDate").data("DateTimePicker").date('@Model.start_date.ToString("MMM dd yyyy HH:mm")');
                $("#finishDate").data("DateTimePicker").date('@Model.finish_date.ToString("MMM dd yyyy HH:mm")');
                $("#companies").trigger("change");
            }
        );
</script>

<div class="container">

    @using (Html.BeginForm("Register", "Batch", new { ReturnUrl = ViewBag.ReturnUrl },
        FormMethod.Post, new {@class="form-signin", enctype = "multipart/form-data" }))
    {
        
        <fieldset>
            <legend>@ViewBag.Title</legend>
            <div>
                @Html.ValidationSummary(false)
            </div>

            <div>
                @Html.ValidationSummary(false)
                @Html.HiddenFor(m => m.created_date)
                @Html.HiddenFor(m => m.revised_date)
                @Html.HiddenFor(m => m.revised_by)
            </div>

            <div style="margin-top:10px">
                @Html.LabelFor(m => m.company_id)
                <select id="companies" name="company_id" class="selectpicker" onchange="GetSKU();GetMachine()">
                    @foreach (DaVinxi.Models.MasterCompanies c in ViewBag.Companies)
                    {
                        <option value="@c.company_id">@c.company_name</option>
                    }
                </select>
            </div>

            <div style="margin-top:10px">
                @Html.LabelFor(m => m.batch_id)
                @Html.TextBoxFor(m => m.batch_id)
                @Html.ValidationMessageFor(m => m.batch_id)
            </div>

            <div style="margin-top:10px">
                <label>Machine</label>
                <select id="machines" name="machine_id" class="selectpicker"></select>
            </div>

            <div>
                <label>SKU</label>
                <select id="skus" name="sku_id" class="selectpicker"></select>
            </div>

            <div style="margin-top:10px">
                @Html.LabelFor(m => m.start_date)
                <div class="input-group date datepicker" id="startDate" data-date-format="MMMM DD YYYY HH:mm">
                    @Html.TextBoxFor(m => m.start_date)
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
                @Html.ValidationMessageFor(m => m.start_date)
            </div>

            <div style="margin-top:10px">
                @Html.LabelFor(m => m.finish_date)
                <div class="input-group date datepicker" id="finishDate">
                    @Html.TextBoxFor(m => m.finish_date)
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
                @Html.ValidationMessageFor(m => m.finish_date)
            </div>

            <div style="margin-top:10px">
                <button class="btn btn-large btn-primary" type="submit">Post</button>
                <button class="btn btn-large btn-default"
                        onclick="location.href='@Url.Action("Index")'" type="button">
                    Cancel
                </button>
            </div>
        </fieldset>
    }

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
</div>

DaVinxi/Views/Batch/Update.cshtml
@model DaVinxi.Models.MasterBatch

@{
    ViewBag.Title = "Update Batch " + Model.batch_id;
}

<script type="text/javascript">
    function GetSKU() {
        $.ajax
            (
                {
                    type: "POST",
                    url: '@Url.Action("GetSKUJSON", "HelperClass")',
                    data: {
                        companyID: $("#companies").val()
                    },
                    dataType: 'json',
                    async: true,
                    beforeSend: function (xhr) {
                        $("#skus").html('');
                    }
                }
            ).done
            (
                function (data) {
                    if (data != null && data.length > 0) {
                        for (var i = 0; i < data.length; i++) {
                            $("#skus").append("<option value='" + data[i].sku_id + "'>[" + data[i].sku_id + "] " +
                                data[i].sku_name + "</option>");
                        }
                    }
                    $("#skus").val('@Model.sku_id');
                    $("#skus").selectpicker("refresh");
                }
            );
    }

    function GetMachine() {
        $.ajax
            (
                {
                    type: "POST",
                    url: '@Url.Action("GetMachinesJSON", "HelperClass")',
                    data: {
                        companyID: $("#companies").val()
                    },
                    dataType: 'json',
                    async: true,
                    beforeSend: function (xhr) {
                        $("#machines").html('');
                    }
                }
            ).done
            (
                function (data) {
                    if (data != null && data.length > 0) {
                        for (var i = 0; i < data.length; i++) {
                            $("#machines").append("<option value='" + data[i].machine.machine_id + "'>" +
                                data[i].machine.machine_name + "</option>");
                        }
                    }
                    $("#machines").val('@Model.machine_id');
                    $("#machines").selectpicker("refresh");
                }
            );
    }

    $
        (
            function () {
                $(".datepicker").datetimepicker(
                    {
                        format: 'MMMM DD YYYY HH:mm'
                    });
                $("#startDate").data("DateTimePicker").date('@Model.start_date.ToString("MMM dd yyyy HH:mm")');
                $("#finishDate").data("DateTimePicker").date('@Model.finish_date.ToString("MMM dd yyyy HH:mm")');

                GetSKU();
                GetMachine();
            }
        );
</script>

<div class="container">

    @using (Html.BeginForm("Update", "Batch", new { ReturnUrl = ViewBag.ReturnUrl },
        FormMethod.Post, new { @class="form-signin" }))
    {
        <fieldset>
            <legend>@ViewBag.Title</legend>

            <div>
                @Html.ValidationSummary(false)
                @Html.HiddenFor(m => m.batch_id, new { id = "batchID" })
                @Html.HiddenFor(m => m.company_id, new { id = "companies" })
                @Html.HiddenFor(m => m.created_date)
                @Html.HiddenFor(m => m.revised_date)
                @Html.HiddenFor(m => m.revised_by)
            </div>

            <div style="margin-top:10px">
                <label>Machine</label>
                <select id="machines" name="machine_id" class="selectpicker"></select>
            </div>

            <div style="margin-top:10px">
                <label>SKU</label>
                <select id="skus" name="sku_id" class="selectpicker"></select>
            </div>

            <div style="margin-top:10px">
                @Html.LabelFor(m => m.start_date)
                <div class="input-group date datepicker" id="startDate">
                    @Html.TextBoxFor(m => m.start_date)
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
                @Html.ValidationMessageFor(m => m.start_date)
            </div>

            <div style="margin-top:10px">
                @Html.LabelFor(m => m.finish_date)
                <div class="input-group date datepicker" id="finishDate">
                    @Html.TextBoxFor(m => m.finish_date)
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
                @Html.ValidationMessageFor(m => m.finish_date)
            </div>

            <div style="margin-top:10px">
                <button class="btn btn-large btn-primary" type="submit">Update</button>
                <button class="btn btn-large btn-default"
                        onclick="location.href='@Url.Action("Index","Batch")'" type="button">
                    Cancel
                </button>
            </div>
        </fieldset>
    }

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
</div>