DaVinxi/Controllers/SKUBusinessController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DaVinxi.Models;

namespace DaVinxi.Controllers
{
    public class SKUBusinessController : Controller
    {
        private MyDBContext _DB;
        public MyDBContext DB
        {
            get
            {
                if (_DB == null)
                    _DB = new MyDBContext();
                return _DB;
            }
        }

        private HelperClassController _Helper;
        public HelperClassController Helper
        {
            get
            {
                if (_Helper == null)
                    _Helper = new HelperClassController(DB);
                return _Helper;
            }
        }

        //
        // GET: /SKUBusiness/
        [Authorize]
        public ActionResult Index()
        {
            int CompanyID = Request.Cookies["company_id"] != null &&
                            int.Parse(Request.Cookies["company_id"].Value) > 0 ?
                            int.Parse(Request.Cookies["company_id"].Value) : 0;

            List<SKUBusinesses> Businesses = Helper.GetSKUBusiness(CompanyID);

            Dictionary<int, string> RelatedCompanies = new Dictionary<int, string>();
            Dictionary<string, List<QualityProperties>> RelatedProperties = new Dictionary<string, List<QualityProperties>>();

            if (Businesses.Count > 0)
            {
                foreach (SKUBusinesses business in Businesses)
                {
                    if (!RelatedCompanies.ContainsKey(business.company_id))
                    {
                        string CompanyName = "All Companies";
                        if (business.company_id > 0)
                        {
                            MasterCompanies Company = DB.Companies.Find(business.company_id);
                            if (Company != null)
                                CompanyName = Company.company_name;
                        }

                        RelatedCompanies.Add(business.company_id, CompanyName);
                    }

                    if (!RelatedProperties.ContainsKey(business.business_id))
                    {
                        List<QualityProperties> QProp =
                            Helper.GetQualityPropertiesBySKUBusiness(business.company_id, business.business_id);
                        if (QProp.Count > 0)
                            RelatedProperties.Add(business.business_id, QProp);
                    }
                }
            }

            ViewBag.RelatedCompanies = RelatedCompanies;
            ViewBag.RelatedProperties = RelatedProperties;

            return View(Businesses);
        }

        [Authorize]
        public ActionResult Register()
        {
            ViewBag.Companies = Helper.GetCompanies(Request.Cookies["company_id"] != null &&
                            int.Parse(Request.Cookies["company_id"].Value) > 0 ?
                            int.Parse(Request.Cookies["company_id"].Value) : 0);
            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult Register(SKUBusinessRegisterModel register)
        {
            if (ModelState.IsValid)
            {
                if (DB.SKUBusiness.Where(q => q.company_id == register.company_id &&
                    string.Compare(q.business_id, register.business_id, true) == 0).Count() > 0)
                    ModelState.AddModelError("exist", "SKU business already exist");
                else
                {
                    SKUBusinesses NewBusiness = new SKUBusinesses();
                    NewBusiness.company_id = register.company_id;
                    NewBusiness.business_id = register.business_id;
                    NewBusiness.business_name = register.business_name;
                    NewBusiness.revised_by = User.Identity.Name;
                    DB.SKUBusiness.Add(NewBusiness);

                    if (Request["properties"] != null)
                    {
                        string[] Properties = Request["properties"].Split(',');
                        if (Properties.Length > 0)
                        {
                            foreach (string prop in Properties)
                            {
                                SKUBusinessProperties BusinessProp = new SKUBusinessProperties();
                                BusinessProp.company_id = NewBusiness.company_id;
                                BusinessProp.business_id = NewBusiness.business_id;
                                BusinessProp.property_id = prop;
                                BusinessProp.created_by = User.Identity.Name;
                                DB.SKUBusinessProperties.Add(BusinessProp);
                            }
                        }
                    }

                    DB.SaveChanges();
                    return RedirectToAction("Index");
                }
            }

            ModelState.AddModelError("", "Cannot register new SKU business");
            return View(register);
        }

        [Authorize]
        public ActionResult Edit(int companyID, string businessID)
        {
            IEnumerable<SKUBusinesses> Businesses = DB.SKUBusiness.Where(q =>
                q.company_id == companyID && string.Compare(q.business_id, businessID, true) == 0);

            if (Businesses.Count() <= 0)
                return RedirectToAction("Index");

            SKUBusinessRegisterModel EditBusiness = new SKUBusinessRegisterModel();
            EditBusiness.company_id = Businesses.ElementAt(0).company_id;
            EditBusiness.business_id = Businesses.ElementAt(0).business_id;
            EditBusiness.business_name = Businesses.ElementAt(0).business_name;

            ViewBag.Properties = Helper.GetQualityProperties(EditBusiness.company_id);

            return View(EditBusiness);
        }

        [Authorize]
        [HttpPost]
        public ActionResult Edit(SKUBusinessRegisterModel edited)
        {
            if (ModelState.IsValid)
            {
                IEnumerable<SKUBusinesses> Businesses = DB.SKUBusiness.Where(q =>
                    q.company_id == edited.company_id && string.Compare(q.business_id, edited.business_id, true) == 0);
                if (Businesses.Count() > 0)
                {
                    bool IsDirty = false;

                    if (string.Compare(Businesses.ElementAt(0).business_name, edited.business_name) != 0)
                    {
                        Businesses.ElementAt(0).business_name = edited.business_name;
                        IsDirty = true;
                    }

                    var SelectedProperties = new HashSet<string>();
                    if (Request["properties"] != null)
                        SelectedProperties = new HashSet<string>(Request["properties"].Split(','));

                    IEnumerable<SKUBusinessProperties> BusinessProp = DB.SKUBusinessProperties.Where(q =>
                        q.company_id == edited.company_id && string.Compare(q.business_id, edited.business_id, true) == 0);

                    var CurrentProperties = new HashSet<string>(BusinessProp.Select(c => c.property_id));

                    IEnumerable<string> NewProperties = SelectedProperties.Where(p => !CurrentProperties.Contains(p));
                    if (NewProperties != null && NewProperties.Count() > 0)
                    {
                        foreach (string prop in NewProperties)
                        {
                            SKUBusinessProperties NewProp = new SKUBusinessProperties();
                            NewProp.company_id = edited.company_id;
                            NewProp.business_id = edited.business_id;
                            NewProp.property_id = prop;
                            NewProp.created_by = User.Identity.Name;

                            DB.SKUBusinessProperties.Add(NewProp);
                            IsDirty = true;
                        }
                    }

                    IEnumerable<SKUBusinessProperties> DeletedProperties = BusinessProp.Where(c =>
                        !SelectedProperties.Contains(c.property_id));
                    if (DeletedProperties != null && DeletedProperties.Count() > 0)
                    {
                        foreach (SKUBusinessProperties deleted in DeletedProperties)
                        {
                            DB.Entry(deleted).State = System.Data.Entity.EntityState.Deleted;
                            IsDirty = true;
                        }
                    }

                    if (IsDirty)
                    {
                        Businesses.ElementAt(0).revised_by = User.Identity.Name;
                        Businesses.ElementAt(0).revised_date = DateTime.Now;

                        DB.Entry(Businesses.ElementAt(0)).State = System.Data.Entity.EntityState.Modified;

                        DB.SaveChanges();
                    }
                }
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Cannot update business information");
            ViewBag.Properties = Helper.GetQualityProperties(edited.company_id);

            return View(edited);
        }

        [Authorize]
        [HttpPost]
        public ActionResult Delete(string businessID, int companyID)
        {
            IEnumerable<SKUBusinesses> Businesses = DB.SKUBusiness.Where(c =>
                c.company_id == companyID && string.Compare(c.business_id, businessID, true) == 0);

            bool IsDirty = false;

            if (Businesses != null && Businesses.Count() > 0)
            {
                DB.Entry(Businesses.ElementAt(0)).State = System.Data.Entity.EntityState.Deleted;
                IsDirty = true;
            }

            IEnumerable<SKUBusinessProperties> Properties = DB.SKUBusinessProperties.Where(p =>

DaVinxi/Views/SKUBusiness/Edit.cshtml
@model DaVinxi.Models.SKUBusinessRegisterModel

@{
    ViewBag.Title = "Edit SKU Business " + Model.business_name;
}

<script type="text/javascript">
    function GetRelatedProperties()
    {
        $.ajax
            (
                {
                    type: "POST",
                    url : '@Url.Action("GetQualityPropertiesBySKUBusinessJSON", "HelperClass")',
                    dataType:'json',
                    data: { companyID: $("#companyID").val(), businessID: $("#businessID").val() }
                }
            ).done
            (
                function(data)
                {
                    if(data!=null && data.length>0)
                    {
                        var Selected = new Array();
                        for(var i=0;i<data.length;i++)
                        {
                            Selected.push(data[i].property_id);
                        }
                        $("#properties").val(Selected);
                    }

                    $("#properties").chosen();
                }
            );
    }

    $
        (
            function ()
            {
                GetRelatedProperties();
            }
        );
</script>

<div class="container">

    @using (Html.BeginForm("Edit", "SKUBusiness", new { ReturnUrl = ViewBag.ReturnUrl },
        FormMethod.Post, new { @class = "form-signin" }))
    {
        <fieldset>
            <legend>@ViewBag.Title</legend>

            <div>
                @Html.ValidationSummary(false)
            </div>

            <div>
                @Html.HiddenFor(m => m.company_id, new { id = "companyID" })
                @Html.HiddenFor(m => m.business_id, new { id = "businessID" })
            </div>

            <div>
                @Html.LabelFor(m => m.business_name)
                @Html.EditorFor(m => m.business_name,
                    new { placeholder = "Business Name" })
                @Html.ValidationMessageFor(m => m.business_name)
            </div>

            <div>
                @Html.Label("Quality Properties")

                <select id="properties" class="chosen-select" name="properties" data-placeholder="Choose Property(ies)" multiple>
                    @foreach (DaVinxi.Models.QualityProperties property in (ViewBag.Properties as List<DaVinxi.Models.QualityProperties>))
                    {
                        <option value="@property.property_id">
                            @property.property_name
                        </option>
                    }
                </select>
            </div>

            <div style="margin-top:10px">
                <button class="btn btn-large btn-primary" type="submit">Post</button>
                <button class="btn btn-large btn-default"
                        onclick="location.href='@Url.Action("Index","SKUBusiness")'" type="button">
                    Cancel
                </button>
            </div>
        </fieldset>
    }

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
</div>

DaVinxi/Views/SKUBusiness/Index.cshtml
@model IEnumerable<DaVinxi.Models.SKUBusinesses>

@{
    ViewBag.Title = "Manage SKU Business";
}

<script type="text/javascript">
    function ShowDeleteDialog(companyID,businessID,fullName)
    {
        $("#delete-message").html("Are you sure want to delete business " + fullName + "?");

        $("#deleted-id").val(businessID);
        $("#deleted-company-id").val(companyID);

        $("#myModal").modal("show");
    }

    $
        (
            function ()
            {
                $("#myModal .deleteConfirmed").click
                (
                    function()
                    {
                        $("#frmDelete").submit();
                    }
                );
            }
        );
</script>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Delete Confirmation</h4>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("Delete", "SKUBusiness", FormMethod.Post, new { id = "frmDelete" }))
                {
                    <input type="hidden" id="deleted-id" name="businessID" />
                    <input type="hidden" id="deleted-company-id" name="companyID" />
                    <div id="delete-message"></div>
                }
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
                <button type="button" class="btn btn-warning deleteConfirmed">Yes</button>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <button class="btn btn-lg btn-default" onclick="location.href='@Url.Action("Register","SKUBusiness")'">
        Add New SKU Business
    </button>

    <table class="table table-bordered table-hover" style="margin-top:15px">
        <thead style="text-align:center">
            <tr>
                <td>
                    @Html.DisplayNameFor(u => u.company_id)
                </td>
                <td>
                    @Html.DisplayNameFor(u => u.business_id)
                </td>
                <td>
                    @Html.DisplayNameFor(u => u.business_name)
                </td>
                <td>
                    Quality Properties
                </td>
                <td>
                    Edit
                </td>
                <td>
                    Delete
                </td>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td style="text-align:center">
                        @if (ViewBag.RelatedCompanies != null &&
                            (ViewBag.RelatedCompanies as Dictionary<int, string>).ContainsKey(item.company_id))
                        {
                            @Html.Label((ViewBag.RelatedCompanies as Dictionary<int, string>)[item.company_id])
                        }
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.business_id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.business_name)
                    </td>
                    <td>
                        @if (ViewBag.RelatedProperties != null &&
                            (ViewBag.RelatedProperties as Dictionary<string, List<DaVinxi.Models.QualityProperties>>).ContainsKey(item.business_id))
                        {
                            <ul>
                                @foreach (var qProp in (ViewBag.RelatedProperties as Dictionary<string, List<DaVinxi.Models.QualityProperties>>)[item.business_id])
                                {
                                    <li>@qProp.property_name</li>
                                }
                            </ul>
                        }
                    </td>
                    <td style="text-align:center">
                        <a href="@Url.Action("Edit", "SKUBusiness",
                            new { companyID = item.company_id, businessID = item.business_id })">
                            <span class="glyphicon glyphicon-pencil"></span>
                        </a>
                    </td>
                    <td style="text-align:center">
                        <a href="javascript:void(0)"
                           onclick="ShowDeleteDialog(@item.company_id,'@item.business_id','@item.business_name')">
                            <span class="glyphicon glyphicon-trash" data-toggle="modal" data-target="#myModal"></span>
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

DaVinxi/Views/SKUBusiness/Register.cshtml
@model DaVinxi.Models.SKUBusinessRegisterModel

@{
    ViewBag.Title = "Register New SKU Business";
}

<script type="text/javascript">
    function GetComponents()
    {
        $.ajax
            (
                {
                    type: "POST",
                    url:'@Url.Action("GetQualityPropertiesJSON", "HelperClass")',
                    dataType:'json',
                    data:{companyID : $("#companyID").val()},
                    beforeSend : function(xhr)
                    {
                        $("#properties").html("");
                        $("#properties").val(new Array());
                    }
                }
            ).done
            (
                function(data)
                {
                    if(data!=null && data.length>0)
                    {
                        for(var i=0;i<data.length;i++)
                        {
                            $("#properties").append("<option value='" + data[i].property_id + "'>"
                                + data[i].property_name + "</option>");
                        }
                    }
                    $(".chosen-select").chosen();
                }
            );
    }

    $(
        function ()
        {
            $("#companyID").trigger("change");
        }
    );
</script>

<div class="container">

    @using (Html.BeginForm("Register", "SKUBusiness", new { ReturnUrl = ViewBag.ReturnUrl },
        FormMethod.Post, new { @class = "form-signin" }))
    {
        <fieldset>
            <legend>@ViewBag.Title</legend>

            <div>
                @Html.ValidationSummary(false)
            </div>

            <div>
                @Html.LabelFor(m => m.company_id)

                <select class="selectpicker" id="companyID" name="company_id" onchange="GetComponents()">
                    @foreach (DaVinxi.Models.MasterCompanies c in ViewBag.Companies)
                    {
                        <option value="@c.company_id">@c.company_name</option>
                    }
                </select>

                @Html.ValidationMessageFor(m => m.company_id)
            </div>

            <div>
                @Html.LabelFor(m => m.business_id)
                @Html.TextBoxFor(m => m.business_id)
                @Html.ValidationMessageFor(m => m.business_id)
            </div>

            <div>
                @Html.LabelFor(m => m.business_name)
                @Html.TextBoxFor(m => m.business_name)
                @Html.ValidationMessageFor(m => m.business_name)
            </div>

            <div>
                @Html.Label("Quality Properties")

                <select class="chosen-select" id="properties" name="properties" data-placeholder="Choose property(ies)" multiple></select>
            </div>

            <div style="margin-top:10px">
                <button class="btn btn-large btn-primary" type="submit">Post</button>
                <button class="btn btn-large btn-default"
                        onclick="location.href='@Url.Action("Index","SKUBusiness")'" type="button">
                    Cancel
                </button>
            </div>
        </fieldset>
    }

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
</div>