DaVinxi/Models/Machine/MachineType/MachineTypeComponents.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DaVinxi.Models
{
    public class MachineTypeComponents
    {
        public MachineTypeComponents()
        {
            created_date = DateTime.Now;
        }

        [Key]
        [Column(Order = 0)]
        [Index("CompanyIndex")]
        public int company_id { get; set; }

        [Key]
        [Column(Order = 1)]
        [Index("MachTypeIndex")]
        public string machine_type_id { get; set; }

        [Key]
        [Column(Order = 2)]
        [Index("ComponentIndex")]
        public string component_id { get; set; }

        [Required]
        public DateTime created_date { get; set; }

        [Required]
        public string created_by { get; set; }
    }
}

DaVinxi/Models/Machine/MachineType/MachineTypeRegisterModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DaVinxi.Models
{
    public class MachineTypeRegisterModel
    {
        [Required]
        [Display(Name = "Company")]
        public int company_id { get; set; }

        [Required]
        [Display(Name = "Machine Type ID")]
        public string machine_type_id { get; set; }

        [Required]
        [Display(Name = "Machine Type Name")]
        public string machine_type_name { get; set; }
    }
}

DaVinxi/Models/Machine/MachineType/MasterMachineType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DaVinxi.Models
{
    public class MasterMachineType
    {
        public MasterMachineType()
        {
            created_date = revised_date = DateTime.Now;
        }

        [Key]
        [Column(Order = 0)]
        [Display(Name = "Company")]
        [Index("CompanyIndex")]
        public int company_id { get; set; }

        [Key]
        [Column(Order = 1)]
        [Display(Name = "Machine Type ID")]
        public string machine_type_id { get; set; }

        [Required]
        [Display(Name = "Machine Type Name")]
        public string machine_type_name { get; set; }

        [Required]
        public DateTime created_date { get; set; }

        [Required]
        public DateTime revised_date { get; set; }

        [Required]
        public string revised_by { get; set; }
    }
}

DaVinxi/Controllers/MachineTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DaVinxi.Models;

namespace DaVinxi.Controllers
{
    public class MachineTypeController : Controller
    {
        private MyDBContext _DB;
        public MyDBContext DB
        {
            get
            {
                if (_DB == null)
                    _DB = new MyDBContext();
                return _DB;
            }
        }

        private HelperClassController _Helper;
        public HelperClassController Helper
        {
            get
            {
                if (_Helper == null)
                    _Helper = new HelperClassController(DB);
                return _Helper;
            }
        }

        //
        // GET: /MachineType/
        [Authorize]
        public ActionResult Index()
        {
            List<MasterMachineType> MachTypes = Helper.GetMachineType(
                Request.Cookies["company_id"] != null && 
                int.Parse(Request.Cookies["company_id"].Value) > 0 ? 
                int.Parse(Request.Cookies["company_id"].Value) : 0);

            Dictionary<int, string> RelatedCompanies = new Dictionary<int, string>();
            Dictionary<string, IList<MasterMachineComponents>> RelatedComponents = 
                new Dictionary<string, IList<MasterMachineComponents>>();

            if (MachTypes != null && MachTypes.Count() > 0)
            {

                foreach (MasterMachineType m in MachTypes)
                {
                    string ID = string.Format("{0}{1}", m.company_id, m.machine_type_id);

                    if (!RelatedComponents.ContainsKey(ID))
                    {
                        RelatedComponents.Add(ID, 
                            Helper.GetMachineComponentByMachineType(m.machine_type_id, m.company_id));
                    }

                    if (!RelatedCompanies.ContainsKey(m.company_id))
                    {
                        String CompanyName = "All Companies";

                        if (m.company_id > 0)
                        {
                            MasterCompanies Company = DB.Companies.Find(m.company_id);
                            if (Company != null)
                                CompanyName = Company.company_name;
                        }

                        RelatedCompanies.Add(m.company_id, CompanyName);
                    }
                }
            }

            ViewBag.RelatedComponents = RelatedComponents;
            ViewBag.RelatedCompanies = RelatedCompanies;

            return View(MachTypes);
        }

        [Authorize]
        public ActionResult Register()
        {
            ViewBag.Companies = Helper.GetCompanies(Request.Cookies["company_id"] != null &&
                int.Parse(Request.Cookies["company_id"].Value) > 0 ?
                int.Parse(Request.Cookies["company_id"].Value) : 0);
            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult Register(MachineTypeRegisterModel register)
        {
            if (ModelState.IsValid)
            {
                if (DB.MachineTypes.Where(m => m.company_id == register.company_id && 
                    string.Compare(m.machine_type_id, register.machine_type_id, true) == 0).Count() > 0)
                    ModelState.AddModelError("exist", "Machine type already exist");
                else
                {
                    MasterMachineType NewMachType = new MasterMachineType();
                    NewMachType.company_id = register.company_id;
                    NewMachType.machine_type_id = register.machine_type_id;
                    NewMachType.machine_type_name = register.machine_type_name;
                    NewMachType.revised_by = User.Identity.Name;

                    DB.MachineTypes.Add(NewMachType);

                    if (Request["components"] != null && Request["components"].Count() > 0)
                    {
                        foreach (string c in Request["components"].ToString().Split(','))
                        {
                            MachineTypeComponents MComponent = new MachineTypeComponents();
                            MComponent.company_id = NewMachType.company_id;
                            MComponent.machine_type_id = NewMachType.machine_type_id;
                            MComponent.component_id = c;
                            MComponent.created_by = User.Identity.Name;

                            DB.MachineTypeComponents.Add(MComponent);
                        }
                    }
                    DB.SaveChanges();
                    return RedirectToAction("Index");
                }
            }

            ModelState.AddModelError("","Cannot add new machine type");
            return View(register);
        }

        [Authorize]
        public ActionResult Edit(int companyID, string id)
        {
            IEnumerable<MasterMachineType> MachType = DB.MachineTypes.Where(m => m.company_id == companyID && string.Compare(id, m.machine_type_id, true) == 0);

            if (MachType != null && MachType.Count() > 0)
            {
                MachineTypeRegisterModel EditMachine = new MachineTypeRegisterModel();
                EditMachine.company_id = MachType.ElementAt(0).company_id;
                EditMachine.machine_type_id = MachType.ElementAt(0).machine_type_id;
                EditMachine.machine_type_name = MachType.ElementAt(0).machine_type_name;

                return View(EditMachine);
            }

            return RedirectToAction("Index");
        }

        [Authorize]
        [HttpPost]
        public ActionResult Edit(MachineTypeRegisterModel editModel)
        {
            if (ModelState.IsValid)
            {
                IEnumerable<MasterMachineType> MachType = DB.MachineTypes.Where(m => 
                    m.company_id == editModel.company_id && 
                    string.Compare(editModel.machine_type_id, m.machine_type_id, true) == 0);

                if (MachType != null && MachType.Count() > 0)
                {
                    bool IsDirty = false;

                    if (string.Compare(editModel.machine_type_name, 
                        MachType.ElementAt(0).machine_type_name) != 0)
                    {
                        IsDirty = true;
                        MachType.ElementAt(0).machine_type_name = editModel.machine_type_name;
                    }

                    if (IsDirty)
                    {
                        MachType.ElementAt(0).revised_date = DateTime.Now;
                        MachType.ElementAt(0).revised_by = User.Identity.Name;
                        DB.Entry(MachType.ElementAt(0)).State = 
                            System.Data.Entity.EntityState.Modified;
                    }

                    if (Request["components"] != null && Request["components"].Length > 0)
                    {
                        List<MachineTypeComponents> RelatedComponent =
                            Helper.GetMachineTypeComponent(
                            MachType.ElementAt(0).machine_type_id, MachType.ElementAt(0).company_id);

                        string[] SplittedComponents = Request["components"].Split(',');

                        var SelectedComponents = new HashSet<string>(SplittedComponents);
                        var CurrentComponents = new HashSet<string>(RelatedComponent.Select(p => p.component_id));

                        IEnumerable<string> NewComponents = SplittedComponents.Where(
                            c => !CurrentComponents.Contains(c));
                        if (NewComponents != null && NewComponents.Count() > 0)
                        {
                            foreach (string c in NewComponents)
                            {
                                MachineTypeComponents NewMachineComponent = new MachineTypeComponents();
                                NewMachineComponent.company_id = MachType.ElementAt(0).company_id;
                                NewMachineComponent.component_id = c;
                                NewMachineComponent.machine_type_id = MachType.ElementAt(0).machine_type_id;
                                NewMachineComponent.created_by = User.Identity.Name;
                                DB.MachineTypeComponents.Add(NewMachineComponent);
                            }
                            IsDirty = true;
                        }

                        IEnumerable<MachineTypeComponents> DeletedComponents = 
                            RelatedComponent.Where(c => 
                            !SelectedComponents.Contains(c.component_id));
                        if (DeletedComponents != null && DeletedComponents.Count() > 0)
                        {
                            foreach (MachineTypeComponents c in DeletedComponents)
                                DB.Entry(c).State = System.Data.Entity.EntityState.Deleted;
                            IsDirty = true;
                        }

                    }

                    if (IsDirty)
                        DB.SaveChanges();
                }

                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Cannot edit machine type");
            return View(editModel);
        }

        [Authorize]
        [HttpPost]
        public ActionResult Delete(string machTypeID, int companyID)
        {
            IEnumerable<MasterMachineType> MachType =
                DB.MachineTypes.Where(m =>
                    string.Compare(machTypeID, m.machine_type_id, true) == 0 &&
                    m.company_id == companyID).ToList();
            if (MachType != null && MachType.Count() > 0)
            {
                DB.Entry(MachType.ElementAt(0)).State = System.Data.Entity.EntityState.Deleted;
                
                IEnumerable<MachineTypeComponents> Components =

DaVinxi/Views/MachineType/Edit.cshtml
@model DaVinxi.Models.MachineTypeRegisterModel

@{
    ViewBag.Title = "Edit MachineType " + Model.machine_type_name;
}

<script type="text/javascript">
    function GetComponents()
    {
        $.ajax
            (
                {
                    type: "POST",
                    url:'@Url.Action("GetComponentsJSON","HelperClass")',
                    dataType:'json',
                    data:{companyID : $("#companyID").val()},
                    beforeSend : function(xhr)
                    {
                        $("#components").html("");
                        $("#components").val(new Array());
                    }
                }
            ).done
            (
                function(data)
                {
                    if(data!=null && data.length>0)
                    {
                        for(var i=0;i<data.length;i++)
                        {
                            $("#components").append("<option value='" + data[i].component_id + "'>" 
                                + data[i].component_name + "</option>");
                        }
                    }
                    GetRelatedComponents();
                }
            );
    }

    function GetRelatedComponents()
    {
        $.ajax
            (
                {
                    type: "POST",
                    url : '@Url.Action("GetMachineTypeComponentJSON","HelperClass")',
                    dataType:'json',
                    data:{machTypeID : $("#machTypeID").val() , companyID : $("#companyID").val()}
                }
            ).done
            (
                function(data)
                {
                    if(data!=null && data.length>0)
                    {
                        var Selected = new Array();
                        for(var i=0;i<data.length;i++)
                        {
                            Selected.push(data[i].component_id);
                        }
                        $("#components").val(Selected);
                    }

                    $("#components").chosen();
                }
            );
    }

    $
        (
            function ()
            {
                GetComponents();
            }
        );
</script>

<div class="container">

    @using (Html.BeginForm("Edit", "MachineType", new { ReturnUrl = ViewBag.ReturnUrl },
        FormMethod.Post, new { @class = "form-signin" }))
    {
        <fieldset>
            <legend>@ViewBag.Title</legend>

            <div>
                @Html.ValidationSummary(false)
            </div>

            <div>
                @Html.HiddenFor(m => m.company_id, new { id = "companyID" })
                @Html.HiddenFor(m => m.machine_type_id, new { id = "machTypeID" })
            </div>

            <div>
                @Html.LabelFor(m => m.machine_type_name)
                @Html.EditorFor(m => m.machine_type_name,
                    new { placeholder = "Machine Type Name" })
                @Html.ValidationMessageFor(m => m.machine_type_name)
            </div>

            <div>
                @Html.Label("Components")

                <select id="components" class="chosen-select" name="components" data-placeholder="Choose Component(s)" multiple>
                </select>
            </div>

            <div style="margin-top:10px">
                <button class="btn btn-large btn-primary" type="submit">Post</button>
                <button class="btn btn-large btn-default"
                        onclick="location.href='@Url.Action("Index","MachineType")'" type="button">
                    Cancel
                </button>
            </div>
        </fieldset>
    }

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
</div>

DaVinxi/Views/MachineType/Index.cshtml
@model IEnumerable<DaVinxi.Models.MasterMachineType>

@{
    ViewBag.Title = "Manage Machine Type";
}

<script type="text/javascript">
    $
        (
            function ()
            {
                $("#myModal .deleteConfirmed").click
                (
                    function()
                    {
                        $("#frmDelete").submit();
                    }
                );
            }
        );

    function ShowDeleteDialog(companyID,machTypeID,fullName)
    {
        $("#delete-message").html
            (
                "Are you sure want to delete components " + fullName + "?"
            );

        $("#deleted-id").val(machTypeID);
        $("#deleted-company-id").val(companyID);

        $("#myModal").modal("show");
    }
</script>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Delete Confirmation</h4>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("Delete", "MachineType", FormMethod.Post, new { id = "frmDelete" }))
                {
                    <input type="hidden" id="deleted-id" name="machTypeID" />
                    <input type="hidden" id="deleted-company-id" name="companyID" />
                    <div id="delete-message"></div>
                }
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
                <button type="button" class="btn btn-warning deleteConfirmed">Yes</button>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <button class="btn btn-lg btn-default" onclick="location.href='@Url.Action("Register","MachineType")'">
        Add New Machine Type
    </button>

    <table class="table table-bordered table-hover" style="margin-top:15px">
        <thead style="text-align:center">
            <tr>
                <td>
                    @Html.DisplayNameFor(u => u.company_id)
                </td>
                <td>
                    @Html.DisplayNameFor(u => u.machine_type_id)
                </td>
                <td>
                    @Html.DisplayNameFor(u => u.machine_type_name)
                </td>
                <td>
                    Components
                </td>
                <td>
                    Edit
                </td>
                <td>
                    Delete
                </td>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td style="text-align:center">
                        @if (ViewBag.RelatedCompanies != null &&
                            (ViewBag.RelatedCompanies as Dictionary<int, string>).ContainsKey(item.company_id))
                        {
                            @Html.Label((ViewBag.RelatedCompanies as Dictionary<int, string>)[item.company_id])
                        }
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.machine_type_id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.machine_type_name)
                    </td>
                    <td>
                        <ul>
                            @if (ViewBag.RelatedComponents != null &&
                            (ViewBag.RelatedComponents as 
                            Dictionary<string, IList<DaVinxi.Models.MasterMachineComponents>>).ContainsKey(
                            string.Format("{0}{1}",item.company_id,item.machine_type_id)))
                            { 
                                foreach (var c in (ViewBag.RelatedComponents as Dictionary<string,
                                    IList<DaVinxi.Models.MasterMachineComponents>>)
                                    [string.Format("{0}{1}", item.company_id, item.machine_type_id)])
                                { 
                                    <li>@c.component_name</li>
                                }
                            }
                        </ul>   
                    </td>
                    <td style="text-align:center">
                        <a href="@Url.Action("Edit", "MachineType",
                            new { companyID = item.company_id, id=item.machine_type_id})">
                            <span class="glyphicon glyphicon-pencil"></span>
                        </a>
                    </td>
                    <td style="text-align:center">
                        <a href="javascript:void(0)"
                           onclick="ShowDeleteDialog(@item.company_id,'@item.machine_type_id','@item.machine_type_name')">
                            <span class="glyphicon glyphicon-trash" data-toggle="modal" data-target="#myModal"></span>
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

DaVinxi/Views/MachineType/Register.cshtml
@model DaVinxi.Models.MachineTypeRegisterModel

@{
    ViewBag.Title = "Register New Machine Type";
}

<script type="text/javascript">
    function GetComponents()
    {
        $.ajax
            (
                {
                    type: "POST",
                    url:'@Url.Action("GetComponentsJSON","HelperClass")',
                    dataType:'json',
                    data:{companyID : $("#companyID").val()},
                    beforeSend : function(xhr)
                    {
                        $("#components").html("");
                        $("#components").val(new Array());
                    }
                }
            ).done
            (
                function(data)
                {
                    if(data!=null && data.length>0)
                    {
                        for(var i=0;i<data.length;i++)
                        {
                            $("#components").append("<option value='" + data[i].component_id + "'>" 
                                + data[i].component_name + "</option>");
                        }
                    }
                    $(".chosen-select").chosen();
                }
            );
    }

    $(
        function ()
        {
            $("#companyID").trigger("change");
        }
    );
</script>

<div class="container">

    @using (Html.BeginForm("Register", "MachineType", new { ReturnUrl = ViewBag.ReturnUrl },
        FormMethod.Post, new { @class = "form-signin" }))
    {
        <fieldset>
            <legend>@ViewBag.Title</legend>

            <div>
                @Html.ValidationSummary(false)
            </div>

            <div>
                @Html.LabelFor(m => m.company_id)

                <select class="selectpicker" id="companyID" name="company_id" onchange="GetComponents()">
                    @foreach (DaVinxi.Models.MasterCompanies c in ViewBag.Companies)
                    {
                        <option value="@c.company_id">@c.company_name</option>
                    }
                </select>

                @Html.ValidationMessageFor(m => m.company_id)
            </div>

            <div>
                @Html.LabelFor(m => m.machine_type_id)
                @Html.TextBoxFor(m => m.machine_type_id,
                    new { placeholder = "Machine Type ID / Initial" })
                @Html.ValidationMessageFor(m => m.machine_type_id)
            </div>

            <div>
                @Html.LabelFor(m => m.machine_type_name)
                @Html.TextBoxFor(m => m.machine_type_name,
                    new { placeholder = "Machine Type Name" })
                @Html.ValidationMessageFor(m => m.machine_type_name)
            </div>

            <div>
                @Html.Label("Components")

                <select class="chosen-select" id="components" name="components" data-placeholder="Choose Component(s)" multiple></select>
            </div>

            <div style="margin-top:10px">
                <button class="btn btn-large btn-primary" type="submit">Post</button>
                <button class="btn btn-large btn-default"
                        onclick="location.href='@Url.Action("Index","MachineType")'" type="button">
                    Cancel
                </button>
            </div>
        </fieldset>
    }

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
</div>