DaVinxi/Controllers/EUController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DaVinxi.Models;

namespace DaVinxi.Controllers
{
    public class EUController : Controller
    {
        private MyDBContext _DB;
        public MyDBContext DB
        {
            get
            {
                if (_DB == null)
                    _DB = new MyDBContext();
                return _DB;
            }
        }

        private HelperClassController _Helper;
        public HelperClassController Helper
        {
            get
            {
                if (_Helper == null)
                    _Helper = new HelperClassController(DB);
                return _Helper;
            }
        }

        //
        // GET: /EU/

        [Authorize]
        public ActionResult Index()
        {
            List<MasterEngineeringUnits> EUs = Helper.GetEngineeringUnits(
                Request.Cookies["company_id"] != null &&
                int.Parse(Request.Cookies["company_id"].Value) > 0 ?
                int.Parse(Request.Cookies["company_id"].Value) : 0);

            Dictionary<int, string> RelatedCompanies = new Dictionary<int, string>();

            foreach (MasterEngineeringUnits eu in EUs)
            {
                if (!RelatedCompanies.ContainsKey(eu.company_id))
                {
                    String CompanyName = "All Companies";

                    if (eu.company_id > 0)
                    {
                        MasterCompanies Company = DB.Companies.Find(eu.company_id);
                        if (Company != null)
                            CompanyName = Company.company_name;
                    }

                    RelatedCompanies.Add(eu.company_id, CompanyName);
                }
            }

            ViewBag.RelatedCompanies = RelatedCompanies;

            return View(EUs);
        }

        [Authorize]
        public ActionResult Register()
        {
            ViewBag.Companies = Helper.GetCompanies(
                Request.Cookies["company_id"] != null &&
                int.Parse(Request.Cookies["company_id"].Value) > 0 ?
                int.Parse(Request.Cookies["company_id"].Value) : 0);
            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult Register(EngineeringUnitRegisterModel register)
        {
            if (ModelState.IsValid)
            {
                if (DB.EngineeringUnits.Where(eu => 
                    eu.company_id == register.company_id && 
                    string.Compare(eu.unit_id, register.unit_id, true) == 0).Count() > 0)
                    ModelState.AddModelError("exist", "Enginerring unit already existed");
                else
                {
                    MasterEngineeringUnits NewEU = new MasterEngineeringUnits();
                    NewEU.company_id = register.company_id;
                    NewEU.unit_id = register.unit_id;
                    NewEU.unit_name = register.unit_name;
                    NewEU.description = register.description;
                    NewEU.revised_by = User.Identity.Name;

                    DB.EngineeringUnits.Add(NewEU);
                    DB.SaveChanges();

                    return RedirectToAction("Index");
                }
            }

            ModelState.AddModelError("", "Cannot register new engineering units");
            return View(register);
        }

        [Authorize]
        public ActionResult Edit(int companyID, string unitID)
        {
            IEnumerable<MasterEngineeringUnits> EUs = DB.EngineeringUnits.Where(eu =>
                    eu.company_id == companyID &&
                    string.Compare(eu.unit_id, unitID, true) == 0);

            if (EUs == null || EUs.Count() <= 0)
                return HttpNotFound();

            EngineeringUnitRegisterModel EditEU = new EngineeringUnitRegisterModel();
            EditEU.company_id = EUs.ElementAt(0).company_id;
            EditEU.unit_id = EUs.ElementAt(0).unit_id;
            EditEU.unit_name = EUs.ElementAt(0).unit_name;
            EditEU.description = EUs.ElementAt(0).description;

            return View(EditEU);
        }

        [Authorize]
        [HttpPost]
        public ActionResult Edit(EngineeringUnitRegisterModel editedEU)
        {
            if (ModelState.IsValid)
            {
                IEnumerable<MasterEngineeringUnits> EUs = DB.EngineeringUnits.Where(eu =>
                    eu.company_id == editedEU.company_id &&
                    string.Compare(eu.unit_id, editedEU.unit_id, true) == 0);

                if (EUs == null || EUs.Count() <= 0)
                    return HttpNotFound();

                bool IsDirty = false;

                if (string.Compare(editedEU.unit_name, EUs.ElementAt(0).unit_name) != 0)
                {
                    EUs.ElementAt(0).unit_name = editedEU.unit_name;
                    IsDirty = true;
                }

                if (string.Compare(editedEU.description, EUs.ElementAt(0).description) != 0)
                {
                    EUs.ElementAt(0).description = editedEU.description;
                    IsDirty = true;
                }

                if (IsDirty)
                {
                    DB.Entry(EUs.ElementAt(0)).State = System.Data.Entity.EntityState.Modified;
                    DB.SaveChanges();
                }
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Cannot update engineering unit");
            return View(editedEU);
        }

        [Authorize]
        [HttpPost]
        public ActionResult Delete(string unitID, int companyID)
        {
            IEnumerable<MasterEngineeringUnits> EUs = DB.EngineeringUnits.Where(eu =>
                        eu.company_id == companyID &&
                        string.Compare(eu.unit_id, unitID, true) == 0);

            if (EUs != null && EUs.Count() > 0)
            {
                DB.Entry(EUs.ElementAt(0)).State = System.Data.Entity.EntityState.Deleted;
                DB.SaveChanges();
            }

            return RedirectToAction("Index");
        }
    }
}

DaVinxi/Views/EU/Edit.cshtml
@model DaVinxi.Models.EngineeringUnitRegisterModel

@{
    ViewBag.Title = "Edit engineering unit " + Model.unit_name;
}

<div class="container">

    @using (Html.BeginForm("Edit", "EU", new { ReturnUrl = ViewBag.ReturnUrl },
        FormMethod.Post, new { @class = "form-signin" }))
    {
        <fieldset>
            <legend>@ViewBag.Title</legend>

            <div>
                @Html.ValidationSummary(false)
            </div>

            <div>
                @Html.HiddenFor(m => m.company_id)
                @Html.HiddenFor(m => m.unit_id)
            </div>

            <div>
                @Html.LabelFor(m => m.unit_name)
                @Html.EditorFor(m => m.unit_name,
                    new { placeholder = "Engineering unit full Name" })
                @Html.ValidationMessageFor(m => m.unit_name)
            </div>

            <div>
                @Html.LabelFor(m => m.description)
                @Html.TextAreaFor(m => m.description,
                new { placeholder = "Description (optional)" })
            </div>

            <div style="margin-top:10px">
                <button class="btn btn-large btn-primary" type="submit">Post</button>
                <button class="btn btn-large btn-default"
                        onclick="location.href='@Url.Action("Index","EU")'" type="button">
                    Cancel
                </button>
            </div>
        </fieldset>
    }

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
</div>

DaVinxi/Views/EU/Index.cshtml
@model IEnumerable<DaVinxi.Models.MasterEngineeringUnits>

@{
    ViewBag.Title = "Manage Engineering Units";
}

<script type="text/javascript">
    $
        (
            function ()
            {
                $("#myModal .deleteConfirmed").click
                (
                    function()
                    {
                        $("#frmDelete").submit();
                    }
                );
            }
        );

    function ShowDeleteDialog(companyID,euID,fullName)
    {
        $("#delete-message").html
            (
                "Are you sure want to delete engineering units " + fullName + "?"
            );

        $("#deleted-id").val(euID);
        $("#deleted-company-id").val(companyID);

        $("#myModal").modal("show");
    }
</script>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Delete Confirmation</h4>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("Delete", "EU", FormMethod.Post, new { id = "frmDelete" }))
                {
                    <input type="hidden" id="deleted-id" name="unitID" />
                    <input type="hidden" id="deleted-company-id" name="companyID" />
                    <div id="delete-message"></div>
                }
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
                <button type="button" class="btn btn-warning deleteConfirmed">Yes</button>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <button class="btn btn-lg btn-default" onclick="location.href='@Url.Action("Register","EU")'">
        Add New Engineering Units
    </button>

    <table class="table table-bordered table-hover" style="margin-top:15px">
        <thead style="text-align:center">
            <tr>
                <td>
                    @Html.DisplayNameFor(u => u.company_id)
                </td>
                <td>
                    @Html.DisplayNameFor(u => u.unit_id)
                </td>
                <td>
                    @Html.DisplayNameFor(u => u.unit_name)
                </td>
                <td>
                    @Html.DisplayNameFor(u => u.description)
                </td>
                <td>
                    Edit
                </td>
                <td>
                    Delete
                </td>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td style="text-align:center">
                        @if (ViewBag.RelatedCompanies != null &&
                            (ViewBag.RelatedCompanies as Dictionary<int, string>).ContainsKey(item.company_id))
                        {
                            @Html.Label((ViewBag.RelatedCompanies as Dictionary<int, string>)[item.company_id])
                        }
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.unit_id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.unit_name)
                    </td>
                    <td>
                        @Html.Raw("<pre>" + Html.Encode(item.description) + "</pre>")
                    </td>
                    <td style="text-align:center">
                        <a href="@Url.Action("Edit", "EU",
                            new { companyID = item.company_id, unitID=item.unit_id})">
                            <span class="glyphicon glyphicon-pencil"></span>
                        </a>
                    </td>
                    <td style="text-align:center">
                        <a href="javascript:void(0)"
                           onclick="ShowDeleteDialog(@item.company_id,'@item.unit_id','@item.unit_name')">
                            <span class="glyphicon glyphicon-trash" data-toggle="modal" data-target="#myModal"></span>
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

DaVinxi/Views/EU/Register.cshtml
@model DaVinxi.Models.EngineeringUnitRegisterModel

@{
    ViewBag.Title = "Register New Engineering Units";
}

<div class="container">

    @using (Html.BeginForm("Register", "EU", new { ReturnUrl = ViewBag.ReturnUrl },
        FormMethod.Post, new { @class = "form-signin" }))
    {
        <fieldset>
            <legend>@ViewBag.Title</legend>

            <div>
                @Html.ValidationSummary(false)
            </div>

            <div>
                @Html.LabelFor(m => m.company_id)

                <select class="selectpicker" name="company_id">
                    @foreach (DaVinxi.Models.MasterCompanies c in ViewBag.Companies)
                    {
                        <option value="@c.company_id">@c.company_name</option>
                    }
                </select>

                @Html.ValidationMessageFor(m => m.company_id)
            </div>

            <div>
                @Html.LabelFor(m => m.unit_id)
                @Html.TextBoxFor(m => m.unit_id,
                    new { placeholder = "Engineering ID / Initial" })
                @Html.ValidationMessageFor(m => m.unit_id)
            </div>

            <div>
                @Html.LabelFor(m => m.unit_name)
                @Html.TextBoxFor(m => m.unit_name,
                    new { placeholder = "Engineering Units Full Name" })
                @Html.ValidationMessageFor(m => m.unit_name)
            </div>

            <div>
                @Html.LabelFor(m => m.description)
                @Html.TextAreaFor(m => m.description,
                new { placeholder = "Description (optional)" })
            </div>

            <div style="margin-top:10px">
                <button class="btn btn-large btn-primary" type="submit">Post</button>
                <button class="btn btn-large btn-default"
                        onclick="location.href='@Url.Action("Index","EU")'" type="button">
                    Cancel
                </button>
            </div>
        </fieldset>
    }

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
</div>